create table if not exists public.sports_picks (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  event_id text not null,
  sport_key text not null,
  sport_title text,
  commence_time timestamptz not null,
  home_team text not null,
  away_team text not null,
  market text not null,
  selection text not null,
  bookmaker text not null,
  american_odds numeric not null,
  model_probability numeric not null,
  market_probability numeric not null,
  edge_pct numeric not null,
  ev_pct numeric not null,
  paper_stake_units numeric not null default 1,
  status text not null default 'open',
  result text,
  closing_odds numeric,
  profit_units numeric,
  model_version text not null default 'v0_market_consensus'
);

create index if not exists sports_picks_created_at_idx on public.sports_picks(created_at desc);
create index if not exists sports_picks_event_id_idx on public.sports_picks(event_id);
